<?php

declare(strict_types=1);

namespace MarekSkopal\ORM\Migrations\Migration;

use MarekSkopal\ORM\Database\DatabaseInterface;
use MarekSkopal\ORM\Database\PostgresDatabase;
use MarekSkopal\ORM\Migrations\Utils\EscapeUtils;
use PDO;

readonly class MigrationRepository
{
    public const string MigrationTable = '__migrations';

    public function __construct(private DatabaseInterface $database)
    {
    }

    public function createMigrationTable(): void
    {
        $q = $this->database->getIdentifierQuoteChar();
        $table = EscapeUtils::escape(self::MigrationTable, $q);

        $idDefinition = $this->database instanceof PostgresDatabase
            ? 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
            : 'INT PRIMARY KEY AUTO_INCREMENT';

        $this->database->getPdo()->query(
            'CREATE TABLE IF NOT EXISTS ' . $table . ' (id ' . $idDefinition . ', name VARCHAR(255) NOT NULL)',
        );
    }

    /** @return list<array{id: int, name: string}> */
    public function getFinishedMigrations(): array
    {
        $q = $this->database->getIdentifierQuoteChar();
        $query = $this->database->getPdo()->query('SELECT * FROM ' . EscapeUtils::escape(self::MigrationTable, $q));
        if ($query === false) {
            throw new \RuntimeException('Failed to fetch migrations');
        }

        // @phpstan-ignore-next-line return.type
        return $query->fetchAll(PDO::FETCH_ASSOC);
    }

    public function insertMigration(string $name): void
    {
        $q = $this->database->getIdentifierQuoteChar();
        $this->database->getPdo()->query(
            'INSERT INTO ' . EscapeUtils::escape(self::MigrationTable, $q) . ' (name) VALUES (\'' . $name . '\')',
        );
    }
}
