<?php

declare(strict_types=1);

namespace MarekSkopal\ORM\Migrations\Tests\Migration\Query\Pgsql;

use MarekSkopal\ORM\Migrations\Migration\Query\Pgsql\PgsqlAlterColumn;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\TestWith;
use PHPUnit\Framework\TestCase;

#[CoversClass(PgsqlAlterColumn::class)]
final class PgsqlAlterColumnTest extends TestCase
{
    /** @param list<string>|null $enum */
    #[TestWith(['id', 'integer', false, false, false, null, null, null, null, null, 'ALTER COLUMN "id" TYPE INTEGER, ALTER COLUMN "id" SET NOT NULL'])]
    #[TestWith(['id', 'integer', true, false, false, null, null, null, null, null, 'ALTER COLUMN "id" TYPE INTEGER, ALTER COLUMN "id" DROP NOT NULL, ALTER COLUMN "id" DROP DEFAULT'])]
    #[TestWith(['id', 'integer', false, true, false, null, null, null, null, null, 'ALTER COLUMN "id" TYPE INTEGER, ALTER COLUMN "id" SET NOT NULL, ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY'])]
    #[TestWith(['id', 'integer', false, false, false, null, null, null, null, 'one', 'ALTER COLUMN "id" TYPE INTEGER, ALTER COLUMN "id" SET NOT NULL, ALTER COLUMN "id" SET DEFAULT \'one\''])]
    #[TestWith(['id', 'varchar', false, false, false, 255, null, null, null, null, 'ALTER COLUMN "id" TYPE VARCHAR(255), ALTER COLUMN "id" SET NOT NULL'])]
    #[TestWith(['id', 'numeric', false, false, false, null, 11, 2, null, 1.1, 'ALTER COLUMN "id" TYPE NUMERIC(11,2), ALTER COLUMN "id" SET NOT NULL, ALTER COLUMN "id" SET DEFAULT \'1.1\''])]
    public function testGetQuery(
        string $name,
        string $type,
        bool $nullable,
        bool $autoincrement,
        bool $primary,
        ?int $size,
        ?int $precision,
        ?int $scale,
        ?array $enum,
        string|int|float|null $default,
        string $expected,
    ): void
    {
        $query = new PgsqlAlterColumn($name, $type, $nullable, $autoincrement, $primary, $size, $precision, $scale, $enum, $default);

        self::assertSame($expected, $query->getQuery());
    }
}
