<?php

declare(strict_types=1);

namespace MarekSkopal\ORM\Migrations\Tests\Migration\Query\Pgsql;

use MarekSkopal\ORM\Migrations\Migration\Query\Pgsql\PgsqlAddColumn;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\TestWith;
use PHPUnit\Framework\TestCase;

#[CoversClass(PgsqlAddColumn::class)]
final class PgsqlAddColumnTest extends TestCase
{
    /** @param list<string>|null $enum */
    #[TestWith(['id', 'integer', false, false, false, null, null, null, null, null, '"id" INTEGER NOT NULL'])]
    #[TestWith(['id', 'integer', true, false, false, null, null, null, null, null, '"id" INTEGER NULL DEFAULT NULL'])]
    #[TestWith(
        ['id', 'integer', false, true, false, null, null, null, null, null, '"id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL'],
    )]
    #[TestWith(['id', 'integer', false, false, true, null, null, null, null, null, '"id" INTEGER NOT NULL PRIMARY KEY'])]
    #[TestWith(['id', 'integer', false, false, false, null, null, null, null, 'one', '"id" INTEGER NOT NULL DEFAULT \'one\''])]
    #[TestWith(['id', 'varchar', false, false, false, 255, null, null, null, null, '"id" VARCHAR(255) NOT NULL'])]
    #[TestWith(['id', 'numeric', false, false, false, null, 11, 2, null, 1.1, '"id" NUMERIC(11,2) NOT NULL DEFAULT \'1.1\''])]
    #[TestWith(
        ['id', 'integer', true, true, true, null, null, null, null, 'default', '"id" INTEGER GENERATED BY DEFAULT AS IDENTITY NULL PRIMARY KEY'],
    )]
    #[TestWith(
        ['type', 'varchar', false, false, false, null, null, null, ['a', 'b', 'c'], 'a', '"type" VARCHAR NOT NULL DEFAULT \'a\' CHECK ("type" IN (\'a\', \'b\', \'c\'))'],
    )]
    public function testGetQuery(
        string $name,
        string $type,
        bool $nullable,
        bool $autoincrement,
        bool $primary,
        ?int $size,
        ?int $precision,
        ?int $scale,
        ?array $enum,
        string|int|float|null $default,
        string $expected,
    ): void
    {
        $query = new PgsqlAddColumn($name, $type, $nullable, $autoincrement, $primary, $size, $precision, $scale, $enum, $default);

        self::assertSame($expected, $query->getQuery());
    }
}
