<?php

declare(strict_types=1);

namespace MarekSkopal\ORM\Migrations\Migration\Query\Pgsql;

use MarekSkopal\ORM\Migrations\Migration\Query\QueryInterface;
use MarekSkopal\ORM\Migrations\Utils\EscapeUtils;

abstract readonly class PgsqlChangeColumn implements QueryInterface
{
    /** @param list<string>|null $enum */
    public function __construct(
        public string $name,
        public string $type,
        public bool $nullable = false,
        public bool $autoincrement = false,
        public bool $primary = false,
        public ?int $size = null,
        public ?int $precision = null,
        public ?int $scale = null,
        public ?array $enum = null,
        public string|int|float|bool|null $default = null,
    ) {
    }

    public function getQuery(): string
    {
        $type = strtoupper($this->type);
        if ($this->size !== null) {
            $type .= '(' . $this->size . ')';
        } elseif ($this->precision !== null && $this->scale !== null) {
            $type .= sprintf('(%d,%d)', $this->precision, $this->scale);
        }

        if ($this->autoincrement) {
            $query = sprintf('%s %s GENERATED BY DEFAULT AS IDENTITY', EscapeUtils::escape($this->name, '"'), $type);
        } else {
            $query = sprintf('%s %s', EscapeUtils::escape($this->name, '"'), $type);
        }

        if ($this->nullable) {
            $query .= ' NULL';
        } else {
            $query .= ' NOT NULL';
        }

        if ($this->primary) {
            $query .= ' PRIMARY KEY';
        }

        if (!$this->autoincrement) {
            if ($this->default !== null) {
                $query .= sprintf(" DEFAULT '%s'", (string) ($this->default === false ? '0' : $this->default));
            } elseif ($this->nullable) {
                $query .= ' DEFAULT NULL';
            }
        }

        if ($this->enum !== null) {
            $query .= sprintf(
                ' CHECK (%s IN (%s))',
                EscapeUtils::escape($this->name, '"'),
                implode(', ', array_map(fn(string $v): string => sprintf("'%s'", $v), $this->enum)),
            );
        }

        return $query;
    }
}
