<?php

declare(strict_types=1);

namespace MarekSkopal\ORM\Migrations\Migration\Query\Pgsql;

use MarekSkopal\ORM\Migrations\Utils\EscapeUtils;

readonly class PgsqlAlterColumn extends PgsqlChangeColumn
{
    /** @return list<string> */
    public function getAlterClauses(): array
    {
        $q = EscapeUtils::escape($this->name, '"');

        $type = strtoupper($this->type);
        if ($this->size !== null) {
            $type .= '(' . $this->size . ')';
        } elseif ($this->precision !== null && $this->scale !== null) {
            $type .= sprintf('(%d,%d)', $this->precision, $this->scale);
        }

        $clauses = [];
        $clauses[] = sprintf('ALTER COLUMN %s TYPE %s', $q, $type);

        if ($this->nullable) {
            $clauses[] = sprintf('ALTER COLUMN %s DROP NOT NULL', $q);
        } else {
            $clauses[] = sprintf('ALTER COLUMN %s SET NOT NULL', $q);
        }

        if ($this->default !== null) {
            $clauses[] = sprintf("ALTER COLUMN %s SET DEFAULT '%s'", $q, (string) ($this->default === false ? '0' : $this->default));
        } elseif ($this->nullable) {
            $clauses[] = sprintf('ALTER COLUMN %s DROP DEFAULT', $q);
        }

        if ($this->autoincrement) {
            $clauses[] = sprintf('ALTER COLUMN %s ADD GENERATED BY DEFAULT AS IDENTITY', $q);
        }

        return $clauses;
    }

    public function getQuery(): string
    {
        return implode(', ', $this->getAlterClauses());
    }
}
